#@ load("@ytt:data", "data")

#@ def labels():
app.kubernetes.io/name: #@ data.values.app_name
app.kubernetes.io/component: main
app.kubernetes.io/part-of: #@ data.values.app_name
app.kubernetes.io/version: #@ data.values.app_version
#@ end

---
apiVersion: v1
kind: Service
metadata:
  namespace: #@ data.values.namespace
  name: #@ data.values.app_name
spec:
  ports:
  - port: #@ data.values.svc_port
    targetPort: #@ data.values.app_port
  selector: #@ labels()
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: #@ data.values.namespace
  name: #@ data.values.app_name
spec:
  replicas: #@ data.values.replicas
  selector:
    matchLabels: #@ labels()
  template:
    metadata:
      labels: #@ labels()
    spec:
      containers:
      - name: #@ data.values.app_name
        image: #@ data.values.app_name
        env:
        - name: HELLO_MSG
          value: #@ data.values.hello_msg
